comida/main/__init__.py
from flask import Blueprint, Flask

bp = Blueprint('main', __name__, template_folder='templates', static_folder='static')


root = Blueprint('root', __name__, template_folder='templates', static_folder='static')

from comida.main import routes

comida/main/routes.py
from . import bp
from flask import redirect, url_for, render_template
from . import root
from .. import login
from flask_login import login_required



@root.route('/')
@root.route('/home')

def index():
    return render_template ('index.html')

@root.route('/profile')
def profile():
    return render_template('profile.html')

@root.route('/pay')
def pay():
    return render_template('pay.html')

comida/main/templates/pay.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Comida | Checkout</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text:wght@500&display=swap" rel="stylesheet" />
    <!-- Stylesheet -->
    <link rel="stylesheet" href="{{url_for('main.static', filename='css/style.css')}}" />
    <!-- Materialize -->
    <link rel="stylesheet" href="{{url_for('main.static', filename='materialize/css/materialize.min.css')}}" />
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{url_for('main.static', filename='fontawesome-free-5.12.0-web/css/all.css')}}" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="{{url_for('main.static', filename='img/favicon.ico')}}" type="image/x-icon" />
</head>

<body>
    <!-- Header & Nav -->
    <div class="navbar-fixed">
        <nav class="teal">
            <div class="container">
                <div class="nav-wrapper">
                    <a href="{{url_for('root.index')}}" class="brand-logo">Comida</a>
                    <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a
            >
            <ul class="right hide-on-med-and-down">
              <li><a href="{{url_for('root.index')}}">Home</a></li>
                    {%if current_user.is_anonymous%}
                    <li><a href="{{url_for('auth.login')}}">Sign Up / Sign In</a></li>
                    {%else%}
                    <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                    {%endif%}
                    <li><a href="#popular-places">Popular Products</a></li>
                    <li><a href="#gallery">Gallery</a></li>
                    <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <ul class="sidenav" id="mobile-nav">
        <li><a href="{{url_for('root.index')}}">Home</a></li>
        {%if current_user.is_anonymous%}
        <li><a href="{{url_for('auth.login')}}">Sign Up / Sign In</a></li>
        {%else%}
        <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
        {%endif%}
        <li><a href="#popular-places">Popular Products</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="#contact">Contact</a></li>
    </ul>

    <!-- Payment -->
    <div class="container">
        <div class="row pay">
            <div>
                <div class="col s12 m5">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{url_for('main.static', filename='img/Veg 01.jpg')}}" alt="Farm Two" />
                        </div>
                        <div class="card-content">
                            <p class="item">Dry Vegetables</p>
                            <p><strong class="bold-text">Price:</strong> $150.00</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6">
                    <div class="checkout">
                        <img src="{{url_for('main.static', filename='img/card 01.jpg')}}" class="responsive-img produce mastercard current" alt="" />
                        <img src="{{url_for('main.static', filename='img/card 02.jpg')}}" class="responsive-img produce visa" alt="" />
                        <img src="{{url_for('main.static', filename='img/card 03.jpg')}}" class="responsive-img produce verve" alt="" />
                        <div class="input-field">
                            <select class="filter-select">
                  <option value="mastercard">Mastercard</option>
                  <option value="visa">Visa</option>
                  <option value="verve">Verve</option>
                </select>
                        </div>
                        <div class="input-field">
                            <input type="text" placeholder="Credit Card Number" />
                        </div>
                        <div class="input-field">
                            <input type="text" placeholder="Card Handler's Name" />
                        </div>
                        <div class="row">
                            <div class="col s12">
                                <div class="input-field">
                                    <input type="text" placeholder="Expiry Date" />
                                </div>
                                <div class="input-field">
                                    <input type="text" placeholder="CVV" />
                                </div>
                            </div>
                        </div>
                        <input type="submit" value="Proceed to Pay" class="btn" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('main.static', filename='jquery/jquery-3.4.1.js')}}"></script>
    <script src="{{url_for('main.static', filename='materialize/js/materialize.min.js')}}"></script>
    <script src="{{url_for('main.static', filename='js/main.js')}}"></script>
    <script src="{{url_for('main.static', filename='js/pay.js')}}"></script>
</body>

</html>

comida/main/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Comida | Profile</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text:wght@500&display=swap" rel="stylesheet" />
    <!-- Stylesheet -->
    <link rel="stylesheet" href="{{url_for('main.static', filename='css/style.css')}}" />
    <!-- Materialize -->
    <link rel="stylesheet" href="{{url_for('main.static', filename='materialize/css/materialize.min.css')}}" />
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="{{url_for('main.static', filename='img/favicon.ico')}}" type="image/x-icon" />
</head>

<body>
    <!-- Header & Nav -->
    <div class="navbar-fixed">
        <nav class="teal">
            <div class="container">
                <div class="nav-wrapper">
                    <a href="{{url_for('main.index')}}" class="brand-logo">Comida</a>
                    <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a
            >
            <ul class="right hide-on-med-and-down">
              <li><a href="{{url_for('main.index')}}">Home</a></li>
                    {%if current_user.is_anonymous%}
                    <li><a href="{{url_for('auth.login')}}">Sign Up / Sign In</a></li>
                    {%else%}
                    <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                    {%endif%}

                    <li><a href="#popular-places">Popular Products</a></li>
                    <li><a href="#gallery">Gallery</a></li>
                    <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <ul class="sidenav" id="mobile-nav">
        <li><a href="{{url_for('main.index')}}">Home</a></li>
        {%if current_user.is_anonymous%}
        <li><a href="{{url_for('auth.login')}}">Sign Up / Sign In</a></li>
        {%else%}
        <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
        {%endif%}
        <li><a href="#popular-places">Popular Products</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="#contact">Contact</a></li>
    </ul>

    <!-- Contact -->
    <div id="contact" class="scrollspy">
        <div class="container">
            <div class="row">
                <div class="col s12 m6 profile">
                    <div class="black-text center">
                        <img class="circle responsive-img" src="{{url_for('main.static', filename='img/profile.png')}}" alt="Profile+Image" width="140px" />
                        <h5>Roli Markovinski</h5>
                        <p>Producer</p>
                        <hr />
                        <div class="details">
                            <div class="det-01">
                                <i class="material-icons small teal-text">mail</i>
                                <h6>email</h6>
                            </div>
                            <p>rolimar@gmail.com</p>
                        </div>
                        <div class="details">
                            <div class="det-01">
                                <i class="material-icons small teal-text">phone</i>
                                <h6>mobile</h6>
                            </div>
                            <p>(+234) 810-9000-100</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6">
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col s2">
                                    <i class="material-icons small teal-text">event</i>
                                </div>
                                <div class="col s7">
                                    <h6>Joined Date</h6>
                                    <p>1 January 2020</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col s2">
                                    <i class="material-icons small teal-text">layers</i>
                                </div>
                                <div class="col s7">
                                    <h6>Popular Products</h6>
                                    <p>10</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col s2">
                                    <i class="material-icons small teal-text">local_shipping</i>
                                </div>
                                <div class="col s7">
                                    <h6>Products Delivered</h6>
                                    <p>150</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="popular-places" class="scrollspy">
                <div class="container">
                    <h4 class="center">
                        <span class="teal-text">Markovinskis'</span> Products
                    </h4>
                    <div class="row veg produce current">
                        <a href="{{url_for('root.pay')}}">
                            <div class="col s12 m4 prod-1">
                                <div class="card">
                                    <div class="card-image">
                                        <img src="{{url_for('main.static', filename='img/Veg 01.jpg')}}" alt="Farm One" />
                                    </div>
                                    <div class="card-content">
                                        <p class="item">Dry Vegetables</p>
                                        <p><strong class="bold-text">Price:</strong> $150.00</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="{{url_for('root.pay')}}">
                            <div class="col s12 m4 prod-1">
                                <div class="card">
                                    <div class="card-image">
                                        <img src="{{url_for('main.static', filename='img/Veg 02.jpg')}}" alt="Farm Two" />
                                    </div>
                                    <div class="card-content">
                                        <p class="item">Wet Vegetables</p>
                                        <p><strong class="bold-text">Price:</strong> $100.00</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="{{url_for('root.pay')}}">
                            <div class="col s12 m4 prod-1">
                                <div class="card">
                                    <div class="card-image">
                                        <img src="{{url_for('main.static', filename='img/Veg 03.jpg')}}" alt="Farm Three" />
                                    </div>
                                    <div class="card-content">
                                        <p class="item">Seasoned Vegetables</p>
                                        <p><strong class="bold-text">Price:</strong> $80.00</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer teal darken-2 white-text center">
        <div class="container">
            <p>Comida &copy; 2020</p>
        </div>
    </footer>

    <script src="{{url_for('main.static', filename='jquery/jquery-3.4.1.js')}}"></script>
    <script src="{{url_for('main.static', filename='materialize/js/materialize.min.js')}}"></script>
    <script src="{{url_for('main.static', filename='js/main.js')}}"></script>
</body>

</html>